---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  SourceBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: '2ntv-mq425-source-bucket'

  DestinationBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: '2ntv-mq425-destination-bucket'

  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: 'LambdaS3AccessPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:GetObject'
                  - 's3:ListBucket'
                  - 's3:PutObject'
                Resource:
                  - 'arn:aws:s3:::2ntv-mq425-source-bucket'
                  - 'arn:aws:s3:::2ntv-mq425-source-bucket/*'
              - Effect: 'Allow'
                Action:
                  - 's3:PutObject'
                Resource:
                  - 'arn:aws:s3:::2ntv-mq425-destination-bucket/*'
              - Effect: 'Allow'
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource:
                  - 'arn:aws:logs:*:*:*'

  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'S3ObjectTransformer'
      Handler: 'index.lambda_handler'
      Role:
        Fn::GetAtt:
          - 'LambdaExecutionRole'
          - 'Arn'
      Code:
        S3Bucket: '2ntv-mq425-lambda-code'
        S3Key: 'index.zip'
      Runtime: 'python3.12'
      Timeout: 300
      Environment:
        Variables:
          SOURCE_BUCKET: 2ntv-mq425-source-bucket
          DESTINATION_BUCKET: 2ntv-mq425-destination-bucket

Outputs:
  SourceBucketName:
    Description: 'Name of the source bucket'
    Value: !Ref SourceBucket

  DestinationBucketName:
    Description: 'Name of the destination bucket'
    Value: !Ref DestinationBucket

  LambdaFunctionArn:
    Description: 'ARN of the Lambda function'
    Value: !GetAtt LambdaFunction.Arn